const data = [
    { option: "Bhaskara", form: "bhaskara", qnt: 3 },
    { option: "Área círculo", form: "Acirculo", qnt: 1 },
    { option: "Área retângulo", form: "Aretangulo", qnt: 2 },
    { option: "Área triângulo", form: "Atriangulo", qnt: 2 },
    { option: "Área triângulo equilátero", form: "AtrianguloEquilatero", qnt: 1 },
    { option: "Área trapézio", form: "Atrapezio", qnt: 3 },
    { option: "Área losango", form: "Alosango", qnt: 2 },
    { option: "Área ângulo triângulo", form: "AanguloTriangulo", qnt: 3 },
    { option: "Fatoração", form: "fatoracao", qnt: 1 },
    { option: "Hipotenusa", form: "hipotenusa", qnt: 2 },
    { option: "Cateto", form: "cateto", qnt: 2 },
    { option: "Perímetro", form: "perimetro", qnt: 2 },
    { option: "Volume cubo", form: "Vcubo", qnt: 1 },
    { option: "Volume paralelepípedo", form: "Vparalelepipedo", qnt: 3 },
    { option: "Volume cilindro", form: "Vcilindro", qnt: 2 },
    { option: "Volume esfera", form: "Vesfera", qnt: 1 },
    { option: "Volume cone", form: "Vcone", qnt: 2 },
    { option: "Volume prisma", form: "Vprisma", qnt: 2 },
    // Adicione outras opções com mensagens personalizadas aqui
];