function dataPtBr() {
    var data = [
        { group: "CÁLCULO", option: "Avaliação", form: "doEval", qnt: 1, exit: 1, placeholder: ["2 + 2"]},
        { group: "CÁLCULO", option: "Bhaskara", form: "bhaskara", qnt: 3, exit: 2, placeholder: ["A", "B", "C"]},
        { group: "CÁLCULO", option: "Função 1° grau", form: "fPrimeiro", qnt: 3, exit: 1, placeholder: ["X", "B", "C"]  },
        { group: "CÁLCULO", option: "Função 2° grau / Exponencial", form: "fSegundo", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"]  },
        { group: "CÁLCULO", option: "Função 2° grau / Logarítmica", form: "fExponencial", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"]  },
        { group: "OPERAÇÕES", option: "Fatoração", form: "fatoracao", qnt: 1, exit: 1, placeholder: []  },
        { group: "ÁREA", option: "Área círculo", form: "Acirculo", qnt: 1, exit: 1, placeholder: ["Raio"]},
        { group: "ÁREA", option: "Área retângulo", form: "Aretangulo", qnt: 2, exit: 1, placeholder: ["Base", "Altura"] },
        { group: "ÁREA", option: "Área triângulo", form: "Atriangulo", qnt: 2, exit: 1, placeholder: ["Base", "Altura"] },
        { group: "ÁREA", option: "Área triângulo equilátero", form: "AtrianguloEquilatero", qnt: 1, exit: 1, placeholder: ["Lado"] },
        { group: "ÁREA", option: "Área trapézio", form: "Atrapezio", qnt: 3, exit: 1, placeholder: ["Base", "base", "Altura"] },
        { group: "ÁREA", option: "Área losango", form: "Alosango", qnt: 2, exit: 1, placeholder: ["Diagonal", "diagonal"] },
        { group: "ÁREA", option: "Área ângulo triângulo", form: "AanguloTriangulo", qnt: 3, exit: 1, placeholder: ["Lado 1", "Lado 2", "Angulo"]  },
        { group: "VOLUME", option: "Volume cubo", form: "Vcubo", qnt: 1, exit: 1, placeholder: ["Lado"]  },
        { group: "VOLUME", option: "Volume paralelepípedo", form: "Vparalelepipedo", qnt: 3, exit: 1, placeholder: ["Largura", "Comprimento", "Altura"]  },
        { group: "VOLUME", option: "Volume cilindro", form: "Vcilindro", qnt: 2, exit: 1, placeholder: ["Raio", "Altura"]  },
        { group: "VOLUME", option: "Volume esfera", form: "Vesfera", qnt: 1, exit: 1, placeholder: ["Raio"]  },
        { group: "VOLUME", option: "Volume cone", form: "Vcone", qnt: 2, exit: 1, placeholder: ["Raio", "Altura"]  },
        { group: "VOLUME", option: "Volume prisma", form: "Vprisma", qnt: 2, exit: 1, placeholder: ["Área da Base", "Altura"]  },
        { group: "GEOMETRIA", option: "Hipotenusa", form: "hipotenusa", qnt: 2, exit: 1, placeholder: ["Cateto", "cateto"]  },
        { group: "GEOMETRIA", option: "Cateto", form: "cateto", qnt: 2, exit: 1, placeholder: ["Cateto", "Hipotenusa"]  },
        { group: "GEOMETRIA", option: "Perímetro", form: "perimetro", qnt: 2, exit: 1, placeholder: ["Lado", "Tamanho"]  },
        { group: "OPERAÇÕES", option: "Soma", form: "soma", qnt: 2, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Subtração", form: "subtracao", qnt: 2, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Multiplicação", form: "multiplicacao", qnt: 2, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Divisão", form: "divisao", qnt: 2, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Exponencial", form: "Math.pow", qnt: 2, exit: 1, placeholder: ["Base", "Expoente"]  },
        { group: "OPERAÇÕES", option: "Raiz", form: "raizQ", qnt: 2, exit: 1, placeholder: ["Radicando", "Índice"]  },
        { group: "OPERAÇÕES", option: "Logarítmo Natural", form: "log", qnt: 1, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Logarítmo Base 10", form: "log10", qnt: 1, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Logarítmo Base 2", form: "log2", qnt: 1, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Inverso", form: "inversao", qnt: 1, exit: 1, placeholder: []  },
        { group: "OPERAÇÕES", option: "Módulo", form: "modulo", qnt: 1, exit: 1, placeholder: []  },
        { group: "GEOMETRIA", option: "Seno", form: "Math.sin", qnt: 1, exit: 1, placeholder: ["Seno"]  },
        { group: "GEOMETRIA", option: "Coseno", form: "Math.cos", qnt: 1, exit: 1, placeholder: ["Coseno"]  },
        { group: "GEOMETRIA", option: "Tangente", form: "Math.tan", qnt: 1, exit: 1, placeholder: ["Tangente"]  },
        { group: "ESPECIAIS", option: "Aleatório", form: "aleatorio", qnt: 2, exit: 1, placeholder: ["Mínimo", "Máximo"] },
        { group: "COMPUTAÇÃO", option: "Bit Shift Zero Esquerda", form: "bitShiftZL", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "Bit Shift Assinado Direita", form: "bitShiftSR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "Bit Shift Zero Direita", form: "bitShiftZR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "E", form: "and", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "OU", form: "or", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "XOR", form: "xor", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: "COMPUTAÇÃO", option: "Não", form: "not", qnt: 1, exit: 1, placeholder: [] },
        { group: "COMPUTAÇÃO", option: "Binário", form: "binario", qnt: 1, exit: 1, placeholder: [] },
        { group: "COMPUTAÇÃO", option: "Hexadecimal", form: "hexadecimal", qnt: 1, exit: 1, placeholder: [] },
        { group: "COMPUTAÇÃO", option: "Octal", form: "octal", qnt: 1, exit: 1, placeholder: [] },
        { group: "COMPUTAÇÃO", option: "Base X", form: "base", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: "COMPUTAÇÃO", option: "Base X para Decimal", form: "basePraDecimal", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: "ESPECIAIS", option: "Faixa", form: "input", type: "range", qnt: 1, exit: 1 },
        { group: "ESPECIAIS", option: "Caixa de Texto", form: "textarea", type: "", qnt: 0, exit: 0}
        // Adicione outras opções com mensagens personalizadas aqui
    ];
    return data;
}

function dataSpMx() {
    var data = [
        { group: 1, option: "Evaluación", form: "doEval", qnt: 1, exit: 1, placeholder: ["2 + 2"]},
        { group: 1, option: "Bhaskara", form: "bhaskara", qnt: 3, exit: 2, placeholder: ["A", "B", "C"]},
        { group: 1, option: "Área círculo", form: "Acirculo", qnt: 1, exit: 1, placeholder: ["Radio"]},
        { group: 1, option: "Área rectángulo", form: "Aretangulo", qnt: 2, exit: 1, placeholder: ["Base", "Altura"] },
        { group: 1, option: "Área triángulo", form: "Atriangulo", qnt: 2, exit: 1, placeholder: ["Base", "Altura"] },
        { group: 1, option: "Área triángulo equilátero", form: "AtrianguloEquilatero", qnt: 1, exit: 1, placeholder: ["Lado"] },
        { group: 1, option: "Área trapecio", form: "Atrapezio", qnt: 3, exit: 1, placeholder: ["Base", "base", "Altura"] },
        { group: 1, option: "Área rombo", form: "Alosango", qnt: 2, exit: 1, placeholder: ["Diagonal", "diagonal"] },
        { group: 1, option: "Área ángulo triángulo", form: "AanguloTriangulo", qnt: 3, exit: 1, placeholder: ["Lado 1", "Lado 2", "Ángulo"]  },
        { group: 1, option: "Factorización", form: "fatoracao", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Hipotenusa", form: "hipotenusa", qnt: 2, exit: 1, placeholder: ["Cateto", "cateto"]  },
        { group: 1, option: "Cateto", form: "cateto", qnt: 2, exit: 1, placeholder: ["Cateto", "Hipotenusa"]  },
        { group: 1, option: "Perímetro", form: "perimetro", qnt: 2, exit: 1, placeholder: ["Lado", "Tamaño"]  },
        { group: 1, option: "Volumen cubo", form: "Vcubo", qnt: 1, exit: 1, placeholder: ["Lado"]  },
        { group: 1, option: "Volumen paralelepípedo", form: "Vparalelepipedo", qnt: 3, exit: 1, placeholder: ["Ancho", "Longitud", "Altura"]  },
        { group: 1, option: "Volumen cilindro", form: "Vcilindro", qnt: 2, exit: 1, placeholder: ["Radio", "Altura"]  },
        { group: 1, option: "Volumen esfera", form: "Vesfera", qnt: 1, exit: 1, placeholder: ["Radio"]  },
        { group: 1, option: "Volumen cono", form: "Vcone", qnt: 2, exit: 1, placeholder: ["Radio", "Altura"]  },
        { group: 1, option: "Volumen prisma", form: "Vprisma", qnt: 2, exit: 1, placeholder: ["Área de la Base", "Altura"]  },
        { group: 1, option: "Suma", form: "soma", qnt: 2, exit: 1, placeholder: []  },
        { group: 1, option: "Resta", form: "subtracao", qnt: 2, exit: 1, placeholder: []  },
        { group: 1, option: "Multiplicación", form: "multiplicacao", qnt: 2, exit: 1, placeholder: []  },
        { group: 1, option: "División", form: "divisao", qnt: 2, exit: 1, placeholder: []  },
        { group: 1, option: "Exponencial", form: "Math.pow", qnt: 2, exit: 1, placeholder: ["Base", "Exponente"]  },
        { group: 1, option: "Raíz", form: "raizQ", qnt: 2, exit: 1, placeholder: ["Radicando", "Índice"]  },
        { group: 1, option: "Logaritmo Natural", form: "log", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Logaritmo Base 10", form: "log10", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Logaritmo Base 2", form: "log2", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Inverso", form: "inversao", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Módulo", form: "modulo", qnt: 1, exit: 1, placeholder: []  },
        { group: 1, option: "Función de 1° grado", form: "fPrimeiro", qnt: 3, exit: 1, placeholder: ["X", "B", "C"]  },
        { group: 1, option: "Función de 2° grado / Exponencial", form: "fSegundo", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"]  },
        { group: 1, option: "Función de 2° grado / Logarítmica", form: "fExponencial", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"]  },
        { group: 1, option: "Seno", form: "Math.sin", qnt: 1, exit: 1, placeholder: ["Seno"]  },
        { group: 1, option: "Coseno", form: "Math.cos", qnt: 1, exit: 1, placeholder: ["Coseno"]  },
        { group: 1, option: "Tangente", form: "Math.tan", qnt: 1, exit: 1, placeholder: ["Tangente"]  },
        { group: 1, option: "Aleatorio", form: "aleatorio", qnt: 2, exit: 1, placeholder: ["Mínimo", "Máximo"] },
        { group: 1, option: "Bit Shift Izquierda Cero", form: "bitShiftZL", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "Bit Shift Derecha Signado", form: "bitShiftSR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "Bit Shift Derecha Cero", form: "bitShiftZR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "Y", form: "and", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "O", form: "or", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "XOR", form: "xor", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "No", form: "not", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Binario", form: "binario", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Hexadecimal", form: "hexadecimal", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Octal", form: "octal", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Base X", form: "base", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: 1, option: "Base X a Decimal", form: "basePraDecimal", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: 1, option: "Rango", form: "input", type: "range", qnt: 1, exit: 1 },
        { group: 1, option: "Área de texto", form: "textarea", type: "", qnt: 0, exit: 0}    
        // Adicione outras opções com mensagens personalizadas aqui
    ];
    return data;
}

function dataEnUs(){
    var data = [
        { group: 1, option: "Evaluation", form: "doEval", qnt: 1, exit: 1, placeholder: ["2 + 2"] },
        { group: 1, option: "Bhaskara", form: "bhaskara", qnt: 3, exit: 2, placeholder: ["A", "B", "C"] },
        { group: 1, option: "Circle Area", form: "Acirculo", qnt: 1, exit: 1, placeholder: ["Radius"] },
        { group: 1, option: "Rectangle Area", form: "Aretangulo", qnt: 2, exit: 1, placeholder: ["Base", "Height"] },
        { group: 1, option: "Triangle Area", form: "Atriangulo", qnt: 2, exit: 1, placeholder: ["Base", "Height"] },
        { group: 1, option: "Equilateral Triangle Area", form: "AtrianguloEquilatero", qnt: 1, exit: 1, placeholder: ["Side"] },
        { group: 1, option: "Trapezoid Area", form: "Atrapezio", qnt: 3, exit: 1, placeholder: ["Base", "Top Base", "Height"] },
        { group: 1, option: "Diamond Area", form: "Alosango", qnt: 2, exit: 1, placeholder: ["Diagonal", "Diagonal"] },
        { group: 1, option: "Triangle Angle Area", form: "AanguloTriangulo", qnt: 3, exit: 1, placeholder: ["Side 1", "Side 2", "Angle"] },
        { group: 1, option: "Factoring", form: "fatoracao", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Hypotenuse", form: "hipotenusa", qnt: 2, exit: 1, placeholder: ["Cathetus", "Cathetus"] },
        { group: 1, option: "Cathetus", form: "cateto", qnt: 2, exit: 1, placeholder: ["Cathetus", "Hypotenuse"] },
        { group: 1, option: "Perimeter", form: "perimetro", qnt: 2, exit: 1, placeholder: ["Side", "Length"] },
        { group: 1, option: "Cube Volume", form: "Vcubo", qnt: 1, exit: 1, placeholder: ["Side"] },
        { group: 1, option: "Parallelepiped Volume", form: "Vparalelepipedo", qnt: 3, exit: 1, placeholder: ["Width", "Length", "Height"] },
        { group: 1, option: "Cylinder Volume", form: "Vcilindro", qnt: 2, exit: 1, placeholder: ["Radius", "Height"] },
        { group: 1, option: "Sphere Volume", form: "Vesfera", qnt: 1, exit: 1, placeholder: ["Radius"] },
        { group: 1, option: "Cone Volume", form: "Vcone", qnt: 2, exit: 1, placeholder: ["Radius", "Height"] },
        { group: 1, option: "Prism Volume", form: "Vprisma", qnt: 2, exit: 1, placeholder: ["Base Area", "Height"] },
        { group: 1, option: "Sum", form: "soma", qnt: 2, exit: 1, placeholder: [] },
        { group: 1, option: "Subtraction", form: "subtracao", qnt: 2, exit: 1, placeholder: [] },
        { group: 1, option: "Multiplication", form: "multiplicacao", qnt: 2, exit: 1, placeholder: [] },
        { group: 1, option: "Division", form: "divisao", qnt: 2, exit: 1, placeholder: [] },
        { group: 1, option: "Exponential", form: "Math.pow", qnt: 2, exit: 1, placeholder: ["Base", "Exponent"] },
        { group: 1, option: "Square Root", form: "raizQ", qnt: 2, exit: 1, placeholder: ["Radical", "Index"] },
        { group: 1, option: "Natural Logarithm", form: "log", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Logarithm Base 10", form: "log10", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Logarithm Base 2", form: "log2", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Inverse", form: "inversao", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Modulus", form: "modulo", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Linear Function", form: "fPrimeiro", qnt: 3, exit: 1, placeholder: ["X", "B", "C"] },
        { group: 1, option: "Quadratic/Exponential Function", form: "fSegundo", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"] },
        { group: 1, option: "Quadratic/Logarithmic Function", form: "fExponencial", qnt: 4, exit: 1, placeholder: ["X", "A", "B", "C"] },
        { group: 1, option: "Sine", form: "Math.sin", qnt: 1, exit: 1, placeholder: ["Sine"] },
        { group: 1, option: "Cosine", form: "Math.cos", qnt: 1, exit: 1, placeholder: ["Cosine"] },
        { group: 1, option: "Tangent", form: "Math.tan", qnt: 1, exit: 1, placeholder: ["Tangent"] },
        { group: 1, option: "Random", form: "aleatorio", qnt: 2, exit: 1, placeholder: ["Minimum", "Maximum"] },
        { group: 1, option: "Bit Shift Zero Left", form: "bitShiftZL", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "Bit Shift Signed Right", form: "bitShiftSR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "Bit Shift Zero Right", form: "bitShiftZR", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "AND", form: "and", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "OR", form: "or", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "XOR", form: "xor", qnt: 2, exit: 1, placeholder: ["X", "Y"] },
        { group: 1, option: "NOT", form: "not", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Binary", form: "binario", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Hexadecimal", form: "hexadecimal", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Octal", form: "octal", qnt: 1, exit: 1, placeholder: [] },
        { group: 1, option: "Base X", form: "base", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: 1, option: "Base X to Decimal", form: "basePraDecimal", qnt: 2, exit: 1, placeholder: ["X", "Base"] },
        { group: 1, option: "Range", form: "input", type: "range", qnt: 1, exit: 1 },
        { group: 1, option: "Text Area", form: "textarea", type: "", qnt: 0, exit: 0 }
        
        // Adicione outras opções com mensagens personalizadas aqui
    ];
    return data;
}